
package Vista;

import Datos.Gastos;
import java.text.DecimalFormat;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FormGasto extends javax.swing.JFrame {
    
    FashionProject m = new FashionProject();
    //MenuEnVentanas mv = new MenuEnVentanas();
    int fila;
    private int id_gasto;
    private String accion="guardar";
    private int totalmesaño=0;
    
    public FormGasto() {
        initComponents();
        this.setLocationRelativeTo(null);
        mostrarListaGastos(0,0);
    }
    
    void ocultar_columnas(){
        tabla.getColumnModel().getColumn(0).setMaxWidth(0);
        tabla.getColumnModel().getColumn(0).setMinWidth(0);
        tabla.getColumnModel().getColumn(0).setPreferredWidth(0);
    }
     
    void habilitar(){
        txtluz.setEnabled(true);
        txtagua.setEnabled(true);
        txtarriendo.setEnabled(true); 
        txtinternet.setEnabled(true); 
        txtotros.setEnabled(true); 
        txtaño.setEnabled(true);
        btnguardar.setEnabled(true);
    }
 
    void mostrarListaGastos(int mes, int año){
        try {
            DefaultTableModel modelo;
            Gastos gto=new Gastos();
            modelo = gto.mostrar(mes, año); 
            tabla.setModel(modelo);
            ocultar_columnas();
            totalmesaño=Integer.parseInt(gto.total.toString());

        } catch (Exception e) {
            JOptionPane.showConfirmDialog(rootPane, e);
        }
    }  
    
    void guardar_o_modificar_gastos(){               
        Gastos gto =new Gastos();
        gto.setLuz(Integer.parseInt(txtluz.getText())); 
        gto.setAgua(Integer.parseInt(txtagua.getText()));
        gto.setArriendo(Integer.parseInt(txtarriendo.getText()));
        gto.setInternet(Integer.parseInt(txtinternet.getText()));
        gto.setOtros(Integer.parseInt(txtotros.getText()));
        
        if (accion.equals("guardar")) {
            if (gto.ingresar(gto)) {
                JOptionPane.showMessageDialog(rootPane, "Gastos registrado satisfactoriamente.");
                mostrarListaGastos(0, 0);
            }
        }
        else if(accion.equals("editar")){
            gto.setId_Gastosmes(id_gasto);
            if (gto.modificar(gto)) {
                JOptionPane.showMessageDialog(rootPane, "Modificado satisfactoriamente.");
                mostrarListaGastos(0,0);
                txtluz.setText("");
                txtagua.setText("");
                txtarriendo.setText("");
                txtinternet.setText("");
                txtotros.setText("");
                accion="guardar";
                btnguardar.setText("Guardar");
            }
        }
    }
    
    void modificarGastos(int fila){
        btnguardar.setText("Guardar Modificación");
        //habilitar();
        accion="editar";
        Gastos gto = new Gastos();
        id_gasto = Integer.parseInt(tabla.getValueAt(fila, 0).toString());
        txtluz.setText(tabla.getValueAt(fila, 1).toString());
        txtagua.setText(tabla.getValueAt(fila, 2).toString());
        txtarriendo.setText(tabla.getValueAt(fila, 3).toString());
        txtinternet.setText(tabla.getValueAt(fila, 4).toString());
        txtotros.setText(tabla.getValueAt(fila, 5).toString());
        
        gto.setId_Gastosmes(id_gasto);
        gto.setLuz(Integer.parseInt(txtluz.getText()));
        gto.setAgua(Integer.parseInt(txtagua.getText()));
        gto.setArriendo(Integer.parseInt(txtarriendo.getText()));
        gto.setInternet(Integer.parseInt(txtinternet.getText()));
        gto.setOtros(Integer.parseInt(txtotros.getText()));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        lbltotalmensual = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        meses = new javax.swing.JComboBox<>();
        jLabel12 = new javax.swing.JLabel();
        txtaño = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        btnsalir = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        txtluz = new javax.swing.JTextField();
        txtagua = new javax.swing.JTextField();
        btnguardar = new javax.swing.JButton();
        txtarriendo = new javax.swing.JTextField();
        btncancelar = new javax.swing.JButton();
        txtinternet = new javax.swing.JTextField();
        txtotros = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel3.setBackground(new java.awt.Color(239, 239, 239));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        lbltotalmensual.setFont(new java.awt.Font("Lucida Grande", 0, 18)); // NOI18N

        tabla = new javax.swing.JTable(){
            public boolean isCellEditable(int rowIndex, int colIndex){
                return false;
            }
        };
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tabla.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        tabla.setFocusable(false);
        tabla.setShowGrid(true);
        tabla.getTableHeader().setReorderingAllowed(false);
        tabla.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tablaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabla);

        jLabel13.setText("Mes");

        jLabel14.setText("Año");

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/Searchtool.png"))); // NOI18N
        jButton1.setText("Buscar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        meses.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione Mes", "Enero", "Febrero", "Marzo", "Abril", "Mayo", "Junio", "Julio", "Agosto", "Septiembre", "Octubre", "Noviembre", "Diciembre" }));

        jLabel12.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel12.setText("Buscar Gasto Por");

        txtaño.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtaño.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtañoActionPerformed(evt);
            }
        });
        txtaño.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtañoKeyTyped(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtañoKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel12)
                        .addGap(40, 40, 40)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel14)
                            .addComponent(jLabel13))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(meses, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 734, Short.MAX_VALUE)
                    .addComponent(lbltotalmensual, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(24, 24, 24))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jLabel12)
                            .addComponent(meses, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel14)
                            .addComponent(txtaño, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(1, 1, 1)
                        .addComponent(jButton1)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 255, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lbltotalmensual, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(16, Short.MAX_VALUE))
        );

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Gestión Gastos");

        btnsalir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/atras.png"))); // NOI18N
        btnsalir.setText("Volver al Menú");
        btnsalir.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnsalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsalirActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Ingresar Gasto"));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Otros");

        txtluz.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtluz.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtluzActionPerformed(evt);
            }
        });
        txtluz.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtluzKeyTyped(evt);
            }
        });

        txtagua.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtagua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtaguaActionPerformed(evt);
            }
        });
        txtagua.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtaguaKeyTyped(evt);
            }
        });

        btnguardar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/gastos 2.png"))); // NOI18N
        btnguardar.setText("Guardar");
        btnguardar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnguardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnguardarActionPerformed(evt);
            }
        });

        txtarriendo.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtarriendo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtarriendoActionPerformed(evt);
            }
        });
        txtarriendo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtarriendoKeyTyped(evt);
            }
        });

        btncancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Files/escoba.png"))); // NOI18N
        btncancelar.setText("Limpiar Campos");
        btncancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btncancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btncancelarActionPerformed(evt);
            }
        });

        txtinternet.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtinternet.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtinternetActionPerformed(evt);
            }
        });
        txtinternet.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtinternetKeyTyped(evt);
            }
        });

        txtotros.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtotros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtotrosActionPerformed(evt);
            }
        });
        txtotros.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtotrosKeyTyped(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("$");

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("$");

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("$");

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("$");

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Luz");

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Agua");

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Arriendo");

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Internet");

        jLabel11.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel11.setText("$");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel6)
                    .addComponent(jLabel5))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(39, 39, 39)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtagua, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtarriendo, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtluz, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jLabel10)
                            .addGap(18, 18, 18)
                            .addComponent(txtinternet, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(txtotros, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(91, 91, 91)
                .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 191, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtluz, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtagua, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtarriendo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9)
                    .addComponent(jLabel4))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(txtinternet, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(txtotros, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 2, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnguardar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btncancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(14, 14, 14))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(14, 14, 14)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnsalir))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(56, Short.MAX_VALUE)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(47, 47, 47))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnsalir, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtluzActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtluzActionPerformed
        txtluz.transferFocus();
    }//GEN-LAST:event_txtluzActionPerformed

    private void txtaguaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtaguaActionPerformed
        txtagua.transferFocus();
    }//GEN-LAST:event_txtaguaActionPerformed

    private void txtarriendoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtarriendoActionPerformed
        txtarriendo.transferFocus();
    }//GEN-LAST:event_txtarriendoActionPerformed

    private void txtinternetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtinternetActionPerformed
        txtinternet.transferFocus();
    }//GEN-LAST:event_txtinternetActionPerformed

    private void tablaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tablaMouseClicked
        fila = tabla.rowAtPoint(evt.getPoint());  //fila donde hago click
        modificarGastos(fila);
    }//GEN-LAST:event_tablaMouseClicked

    private void btnguardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnguardarActionPerformed
        if(txtluz.getText().length()>0 || txtagua.getText().length()>0 || txtarriendo.getText().length()>0 || txtinternet.getText().length()>0 || txtotros.getText().length()>0){
            if(txtluz.getText().equals("")) txtluz.setText("0");
            if(txtagua.getText().equals("")) txtagua.setText("0");
            if(txtarriendo.getText().equals("")) txtarriendo.setText("0");
            if(txtinternet.getText().equals("")) txtinternet.setText("0");
            if(txtotros.getText().equals("")) txtotros.setText("0");
            guardar_o_modificar_gastos();
            txtluz.setText("");
            txtagua.setText("");
            txtarriendo.setText("");
            txtinternet.setText("");
            txtotros.setText("");
            accion="guardar";
            btnguardar.setText("Guardar");
        }
        else{
            JOptionPane.showMessageDialog(rootPane, "No ha ingresado gastos.");
        }
    }//GEN-LAST:event_btnguardarActionPerformed

    private void btncancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btncancelarActionPerformed
        txtluz.setText("");
        txtagua.setText("");
        txtarriendo.setText("");
        txtinternet.setText("");
        txtotros.setText("");
        accion="guardar";
        btnguardar.setText("Guardar");
    }//GEN-LAST:event_btncancelarActionPerformed

    private void btnsalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsalirActionPerformed
        //this.dispose();
        m.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_btnsalirActionPerformed

    private void txtañoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtañoKeyReleased

    }//GEN-LAST:event_txtañoKeyReleased

    private void txtotrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtotrosActionPerformed
        txtotros.transferFocus();
    }//GEN-LAST:event_txtotrosActionPerformed

    private void txtañoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtañoActionPerformed

    }//GEN-LAST:event_txtañoActionPerformed

    private void txtluzKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtluzKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtluz.getText().length()>=9) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtluzKeyTyped

    private void txtaguaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtaguaKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtagua.getText().length()>=9) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtaguaKeyTyped

    private void txtarriendoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtarriendoKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtarriendo.getText().length()>=9) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtarriendoKeyTyped

    private void txtinternetKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtinternetKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtinternet.getText().length()>=9) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtinternetKeyTyped

    private void txtotrosKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtotrosKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtotros.getText().length()>=9) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtotrosKeyTyped

    private void txtañoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtañoKeyTyped
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c))) evt.consume();    
        if(txtaño.getText().length()>=4) evt.consume();  // valido que no sea mayor que 9 digitos
    }//GEN-LAST:event_txtañoKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String mes_combo = meses.getSelectedItem().toString();
        int mes_int=0;
        
        if(txtaño.getText().length()==0 || mes_combo.equals("Seleccione Mes")){
            if(mes_combo.equals("Seleccione Mes")){
                JOptionPane.showConfirmDialog(rootPane, "Debe ingresar mes.","",JOptionPane.WARNING_MESSAGE);
                meses.requestFocus();
                return;
            }
            if(txtaño.getText().length()==0){
                JOptionPane.showConfirmDialog(rootPane, "Debe ingresar año.","",JOptionPane.WARNING_MESSAGE);
                txtaño.requestFocus();
                return;
            }
        }else if(txtaño.getText().length()>0 && !(mes_combo.equals("Seleccione Mes"))){
            if(mes_combo.equals("Seleccione Mes")) mes_int=0;
            if(mes_combo.equals("Enero")) mes_int=1;
            if(mes_combo.equals("Febrero")) mes_int=2;
            if(mes_combo.equals("Marzo")) mes_int=3;
            if(mes_combo.equals("Abril")) mes_int=4;
            if(mes_combo.equals("Mayo")) mes_int=5;
            if(mes_combo.equals("Junio")) mes_int=6;
            if(mes_combo.equals("Julio")) mes_int=7;
            if(mes_combo.equals("Agosto")) mes_int=8;
            if(mes_combo.equals("Septiembre")) mes_int=9;
            if(mes_combo.equals("Octubre")) mes_int=10;
            if(mes_combo.equals("Noviembre")) mes_int=11;
            if(mes_combo.equals("Diciembre")) mes_int=12;

            mostrarListaGastos(mes_int, Integer.parseInt(txtaño.getText()));
            DecimalFormat formateador = new DecimalFormat("###,###.###");
            
            lbltotalmensual.setText("Total gasto "+mes_combo+"-"+Integer.parseInt(txtaño.getText())+": $ "+formateador.format(totalmesaño));
            
            /*if((mes_int!=0) && (txtaño.getText().length()>0)){
                mostrarListaGastos(mes_int, Integer.parseInt(txtaño.getText()));
            }
            else if(mes_int == 0){
                mostrarListaGastos(0, Integer.parseInt(txtaño.getText()));
            }
            else if(txtaño.getText().length() == 0){
                mostrarListaGastos(mes_int, 0);
            }*/
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btncancelar;
    private javax.swing.JButton btnguardar;
    private javax.swing.JButton btnsalir;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lbltotalmensual;
    private javax.swing.JComboBox<String> meses;
    private javax.swing.JTable tabla;
    private javax.swing.JTextField txtagua;
    private javax.swing.JTextField txtarriendo;
    private javax.swing.JTextField txtaño;
    private javax.swing.JTextField txtinternet;
    private javax.swing.JTextField txtluz;
    private javax.swing.JTextField txtotros;
    // End of variables declaration//GEN-END:variables
}
